import type { Metadata } from "next";
import { Montserrat, Poppins } from "next/font/google";
import '@/styles/globals.scss'
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import HomeLayout from "@/layouts/HomeLayout";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({ weight: ["200","400","500", "600", "700", "800"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ReactQueryProvider>
          <HomeLayout>
            <Toaster position="bottom-center" />
            {children}
          </HomeLayout>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
